name: Copilot Setup Steps

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-environment:
    name: Setup Development Environment
    runs-on: vscode-large-runners
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.x'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      - name: Install Python setuptools
        run: pip install setuptools

      - name: Install dependencies
        run: npm ci

      - name: Check environment requirements
        run: npm run check-env

      - name: Verify installation
        run: |
          node --version
          npm --version
          python --version
          dotnet --version